// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUBD_books_project.DB_Classes;

namespace SUBD_books_project.Migrations
{
    [DbContext(typeof(db_books_conandoyleContext))]
    [Migration("20241214115350_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SUBD_books_project.DB_Classes.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPublishingHouse")
                        .HasColumnName("id_publishing_house")
                        .HasColumnType("int");

                    b.Property<int>("Pages")
                        .HasColumnName("pages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdPublishingHouse");

                    b.ToTable("books");
                });

            modelBuilder.Entity("SUBD_books_project.DB_Classes.PublishingHouses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("publishing_houses");
                });

            modelBuilder.Entity("SUBD_books_project.DB_Classes.Books", b =>
                {
                    b.HasOne("SUBD_books_project.DB_Classes.PublishingHouses", "IdPublishingHouseNavigation")
                        .WithMany("Books")
                        .HasForeignKey("IdPublishingHouse")
                        .HasConstraintName("FK__books__id_publis__46E78A0C")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
